import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'

import { getImageUrl } from '../utils/firebase/initFirebase'

import styles from '../styles/Home.module.css'

import LogoAccessmatic from '../public/images/logo.png'
import MulticorpLogo from '../public/images/multicorp-logo.svg'
import MenuItem from '../components/atoms/MenuItem'
import MenuPpal from '../components/molecules/MenuPpal'
import Filter from '../components/organisms/filter'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header className={styles.headerWrapper}>
          <MenuPpal />
          <div className={styles.logosWrapper}>
            <div className={styles.logos}>
              <Image
                src={MulticorpLogo}
                alt='logo'
              />
              <Image
                src={LogoAccessmatic}
                alt='logo'
                width={510}
                height={54}
              />
            </div>
          </div>
        </header>
        <Filter />
        {/* {urlImage !== '' && (
          <Image
            src={urlImage}
            alt='logo'
            width={1200}
            height={900}
          />
        )} */}
      </main>
      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
